apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: quay.io/your-username/database:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "VdZDPFXDxpedA123"
        - name: MYSQL_DATABASE
          value: "management"
        - name: MYSQL_USER
          value: "ubuntu"
        - name: MYSQL_PASSWORD
          value: "VdZDPFXDxpedA123"
        - name:  MARIADB_ROOT_PASSWORD
          value: my-secret-pw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: quay.io/med_chiheb/front:latest
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: ClusterIP
  ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentificat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentificat
  template:
    metadata:
      labels:
        app: authentificat
    spec:
      containers:
      - name: authentificat
        image: quay.io/med_chiheb/auth:latest
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: authentificat
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: quay.io/med_chiheb/user:latest
        ports:
        - containerPort: 8096
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
  type: ClusterIP
