---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: quay.io/med_chiheb/front:latest
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: front-route
spec:
  to:
    kind: Service
    name: front-service
  port:
    targetPort: 4200
  tls:
    termination: edge
